In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('training.csv')

In [3]:
df.head()

,row_id,security_id,p_tcount,p_value,trade_vwap,trade_volume,initiator,transtype1,time1,bid1,...,bid96,ask96,bid97,ask97,bid98,ask98,bid99,ask99,bid100,ask100
0,1,1,9154,6831386312,2395.0,887,B,Q,08:00:20.799,2225.0,...,2397.0,2399.0,2397.0,2399.0,2397.0,2399.0,2397.0,2398.0,2397.5,2398.0
1,2,1,9154,6831386312,2398.0,748,B,Q,08:00:21.996,2393.0,...,2398.0,2399.0,2398.0,2399.0,2397.0,2399.0,2397.0,2398.0,2397.0,2398.0
2,3,1,9154,6831386312,2398.0,151,B,T,08:00:29.200,2393.0,...,2397.0,2398.0,2397.0,2399.0,2397.0,2399.0,2397.0,2398.0,2397.0,2398.0
3,4,1,9154,6831386312,2398.5,110,S,Q,08:00:31.073,2393.0,...,2397.0,2398.0,2397.0,2398.0,2397.0,2398.0,2397.0,2399.0,2398.0,2399.0
4,5,1,9154,6831386312,2398.0,108,B,T,08:00:31.867,2393.0,...,2398.0,2399.0,2397.0,2399.0,2397.0,2398.0,2397.0,2398.0,2397.0,2398.0

In [5]:
list(df.columns)

['row_id',
 'security_id',
 'p_tcount',
 'p_value',
 'trade_vwap',
 'trade_volume',
 'initiator',
 'transtype1',
 'time1',
 'bid1',
 'ask1',
 'transtype2',
 'time2',
 'bid2',
 'ask2',
 'transtype3',
 'time3',
 'bid3',
 'ask3',
 'transtype4',
 'time4',
 'bid4',
 'ask4',
 'transtype5',
 'time5',
 'bid5',
 'ask5',
 'transtype6',
 'time6',
 'bid6',
 'ask6',
 'transtype7',
 'time7',
 'bid7',
 'ask7',
 'transtype8',
 'time8',
 'bid8',
 'ask8',
 'transtype9',
 'time9',
 'bid9',
 'ask9',
 'transtype10',
 'time10',
 'bid10',
 'ask10',
 'transtype11',
 'time11',
 'bid11',
 'ask11',
 'transtype12',
 'time12',
 'bid12',
 'ask12',
 'transtype13',
 'time13',
 'bid13',
 'ask13',
 'transtype14',
 'time14',
 'bid14',
 'ask14',
 'transtype15',
 'time15',
 'bid15',
 'ask15',
 'transtype16',
 'time16',
 'bid16',
 'ask16',
 'transtype17',
 'time17',
 'bid17',
 'ask17',
 'transtype18',
 'time18',
 'bid18',
 'ask18',
 'transtype19',
 'time19',
 'bid19',
 'ask19',
 'transtype20',
 'time20',
 'bid20',
 'ask20',
 'transtype21',
 'time21',
 'bid21',
 'ask21',
 'transtype22',
 'time22',
 'bid22',
 'ask22',
 'transtype23',
 'time23',
 'bid23',
 'ask23',
 'transtype24',
 'time24',
 'bid24',
 'ask24',
 'transtype25',
 'time25',
 'bid25',
 'ask25',
 'transtype26',
 'time26',
 'bid26',
 'ask26',
 'transtype27',
 'time27',
 'bid27',
 'ask27',
 'transtype28',
 'time28',
 'bid28',
 'ask28',
 'transtype29',
 'time29',
 'bid29',
 'ask29',
 'transtype30',
 'time30',
 'bid30',
 'ask30',
 'transtype31',
 'time31',
 'bid31',
 'ask31',
 'transtype32',
 'time32',
 'bid32',
 'ask32',
 'transtype33',
 'time33',
 'bid33',
 'ask33',
 'transtype34',
 'time34',
 'bid34',
 'ask34',
 'transtype35',
 'time35',
 'bid35',
 'ask35',
 'transtype36',
 'time36',
 'bid36',
 'ask36',
 'transtype37',
 'time37',
 'bid37',
 'ask37',
 'transtype38',
 'time38',
 'bid38',
 'ask38',
 'transtype39',
 'time39',
 'bid39',
 'ask39',
 'transtype40',
 'time40',
 'bid40',
 'ask40',
 'transtype41',
 'time41',
 'bid41',
 'ask41',
 'transtype42',
 'time42',
 'bid42',
 'ask42',
 'transtype43',
 'time43',
 'bid43',
 'ask43',
 'transtype44',
 'time44',
 'bid44',
 'ask44',
 'transtype45',
 'time45',
 'bid45',
 'ask45',
 'transtype46',
 'time46',
 'bid46',
 'ask46',
 'transtype47',
 'time47',
 'bid47',
 'ask47',
 'transtype48',
 'time48',
 'bid48',
 'ask48',
 'transtype49',
 'time49',
 'bid49',
 'ask49',
 'transtype50',
 'time50',
 'bid50',
 'ask50',
 'bid51',
 'ask51',
 'bid52',
 'ask52',
 'bid53',
 'ask53',
 'bid54',
 'ask54',
 'bid55',
 'ask55',
 'bid56',
 'ask56',
 'bid57',
 'ask57',
 'bid58',
 'ask58',
 'bid59',
 'ask59',
 'bid60',
 'ask60',
 'bid61',
 'ask61',
 'bid62',
 'ask62',
 'bid63',
 'ask63',
 'bid64',
 'ask64',
 'bid65',
 'ask65',
 'bid66',
 'ask66',
 'bid67',
 'ask67',
 'bid68',
 'ask68',
 'bid69',
 'ask69',
 'bid70',
 'ask70',
 'bid71',
 'ask71',
 'bid72',
 'ask72',
 'bid73',
 'ask73',
 'bid74',
 'ask74',
 'bid75',
 'ask75',
 'bid76',
 'ask76',
 'bid77',
 'ask77',
 'bid78',
 'ask78',
 'bid79',
 'ask79',
 'bid80',
 'ask80',
 'bid81',
 'ask81',
 'bid82',
 'ask82',
 'bid83',
 'ask83',
 'bid84',
 'ask84',
 'bid85',
 'ask85',
 'bid86',
 'ask86',
 'bid87',
 'ask87',
 'bid88',
 'ask88',
 'bid89',
 'ask89',
 'bid90',
 'ask90',
 'bid91',
 'ask91',
 'bid92',
 'ask92',
 'bid93',
 'ask93',
 'bid94',
 'ask94',
 'bid95',
 'ask95',
 'bid96',
 'ask96',
 'bid97',
 'ask97',
 'bid98',
 'ask98',
 'bid99',
 'ask99',
 'bid100',
 'ask100']